---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Instalar prerequisitos
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instalar paquetes LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

    - name: Crear document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Configurar Apache virtualhost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Habilitar nuevo sitio
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Deshabilitar sitio por defecto Apache
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Establecer el password de root
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Borrar todas las cuentas de usuarios anonimos
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Borrar la base de datos de prueba de MySQL
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: "UFW - Permitir HTTP en el puerto {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: Configurar pagina de informacion de PHP
      template:
        src: "files/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

  handlers:
    - name: Recargar Apache
      service:
        name: apache2
        state: reloaded

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
